modLoader="javafml"
loaderVersion="[45,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/Autovw/MoreConcrete/issues"

[[mods]]
modId="moreconcrete"
version="1.4.5"
displayName="More Concrete"
updateJSONURL="https://raw.githubusercontent.com/Autovw/ModUpdates/main/moreconcrete/update.json"
displayURL="https://github.com/Autovw/MoreConcrete/wiki"
logoFile="more_concrete_banner.png"
#credits=""
authors="Autovw"
description='''
A simple mod that adds more concrete variants into Minecraft!
'''

[[dependencies.moreconcrete]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moreconcrete]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"

[modproperties.moreconcrete]
    catalogueItemIcon="moreconcrete:light_blue_concrete_stairs" #Optional support for Cataloque mod.
    configuredBackground="minecraft:textures/block/light_blue_concrete.png" #Optional support for Configured mod.
