modLoader="javafml"
loaderVersion="[2,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/Autovw/MoreConcrete/issues"

[[mods]]
modId="moreconcrete"
version="${mod_version}"
displayName="More Concrete"
updateJSONURL="https://raw.githubusercontent.com/Autovw/ModUpdates/main/moreconcrete/update.json"
displayURL="https://github.com/Autovw/MoreConcrete/wiki"
logoFile="more_concrete_banner.png"
#credits=""
authors="Autovw"
description='''
A simple mod that adds more concrete variants into Minecraft!
'''

[[dependencies.moreconcrete]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.1-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moreconcrete]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="NONE"
    side="BOTH"

[modproperties.moreconcrete]
    catalogueItemIcon="moreconcrete:light_blue_concrete_stairs" #Optional support for Cataloque mod.
    configuredBackground="minecraft:textures/block/light_blue_concrete.png" #Optional support for Configured mod.
